# Configuration file for MegaLinter
DISABLE:
  - COPYPASTE
ENABLE_LINTERS:
  - JAVA_CHECKSTYLE
  - XML_XMLLINT
  - SPELL_MISSPELL
PRINT_ALL_FILES: false
JAVA_CHECKSTYLE_FILE_EXTENSIONS:
  - ".java"
JAVA_CHECKSTYLE_FILE_NAME: "checkstyle-config.xml"
XML_XMLLINT_FILE_EXTENSIONS:
  - ".XML"
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|TEMPLATES)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.automation/generated|docs/descriptors)'
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true
JSON_REPORTER: true
TEXT_REPORTER: true
PRINT_ALPACA: false