name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
    
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Change wrapper permissions
        run: |
          cd android/Drawer
          chmod +x gradlew
      
      - name: Build with Gradle
        run: |
          cd android/Drawer
          ./gradlew build --stacktrace
