name: Android CI

on:
  push:
    paths:
      - 'android/**'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
    
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Change wrapper permissions
        run: |
          cd android/Drawer
          chmod +x gradlew
      
      - name: Build with Gradle
        run: |
          cd android/Drawer
          ./gradlew build --stacktrace
          
          
  run-unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
    
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Change wrapper permissions
        run: |
          cd android/Drawer
          chmod +x gradlew    
          
      - name: Run unit tests
        run: |
          cd android/Drawer
          ./gradlew test --info
          
      # Upload artifacts
      - name: Archive test artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit test reports
          path: |
            report
            unit-tests.log
          
          
  run-instrumented-tests:
    runs-on: macos-latest
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
    
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
       
      - name: Change wrapper permissions
        run: |
          cd android/Drawer
          chmod +x gradlew
       
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Pixel 5
          api-level: 31
          arch: x86_64
          working-directory: ./android/Drawer
          script: cd android/Drawer && ./gradlew connectedAndroidTest
          
      # Upload artifacts
      - name: Archive test artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Instrumented test reports
          path: |
            report
            instrumented-tests.log