name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: |
        cd android/Drawer
        ./gradlew build --stacktrace
