name: Java Linter

on:
  push:
    paths:
      - 'android/**'
      - 'tools/**'
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          tool_name: 'reviewdog'
          checkstyle_config: '.github/chekstyle-config.txt'
