name: Java CI

on:
  push:
    paths:
      - 'tools/**'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Change wrapper permissions
        run: |
          cd tools/mqtt-testing
          chmod +x gradlew
      
      - name: Build with Gradle
        run: |
          cd tools/mqtt-testing
          ./gradlew build --stacktrace
          